services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SMS\FluidComponents\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    SMS\FluidComponents\Command\GenerateXsdCommand:
        tags:
            -   name: 'console.command'
                command: 'fluidcomponents:generatexsd'
                description: 'Generates the XSD files for autocompletion in the IDE.'
                schedulable: true
                hidden: false

    SMS\FluidComponents\Command\CheckContentEscapingCommand:
        tags:
            -   name: 'console.command'
                command: 'fluidcomponents:checkContentEscaping'
                description: 'Checks for possible escaping issues with content parameter due to new children escaping behavior'
                schedulable: false
                hidden: false
